INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("8k Projector","Electronics",500000,"2018-06-01","2018-09-15");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Comfy Socks", "Clothing",25000,"2016-1-01","2016-01-31");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Super Dongle","Electronics",100000,"2017-05-01","2017-08-31");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Best Dress Shirt","Clothing",60000,"2017-06-01","2017-12-31");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Fidget Spinner","Toys",10000,"2017-01-01","2017-02-28");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Wireless Earbuds","Electronics",100000,"2018-04-01","2018-09-30");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Cooking Classes","Education",15000,"2015-07-01","2015-09-30");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Heated Blanket","Home",40000,"2016-07-01","2016-11-30");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Vegan Leather Couch","Home",80000,"2017-03-01","2017-09-01");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Cabbage Patch Kids","Toys",35000,"2018-06-15","2018-10-15");

INSERT INTO users (name,age) VALUES ("Bobby Flay",54);
INSERT INTO users (name,age) VALUES ("Vincent Valentine",26);
INSERT INTO users (name,age) VALUES ("Matz Ruby",47);
INSERT INTO users (name,age) VALUES ("Simon Bolivar",62);
INSERT INTO users (name,age) VALUES ("Christopher Robin",39);
INSERT INTO users (name,age) VALUES ("Robert Johnson",29);
INSERT INTO users (name,age) VALUES ("Abby Clarmont",18);
INSERT INTO users (name,age) VALUES ("Claire Mok",30);
INSERT INTO users (name,age) VALUES ("Shirley Temple",78);
INSERT INTO users (name,age) VALUES ("Kevin Fultz",40);
INSERT INTO users (name,age) VALUES ("Ben Chen",23);
INSERT INTO users (name,age) VALUES ("Michael Jordan",55);
INSERT INTO users (name,age) VALUES ("Michael Bay",64);
INSERT INTO users (name,age) VALUES ("Daisy McAllister",46);
INSERT INTO users (name,age) VALUES ("Emily Blunt",38);
INSERT INTO users (name,age) VALUES ("George Black",50);
INSERT INTO users (name,age) VALUES ("Emma Short",25);
INSERT INTO users (name,age) VALUES ("Lily Abby",29);
INSERT INTO users (name,age) VALUES ("Frank River",57);
INSERT INTO users (name,age) VALUES ("Victoria Dark",31);

INSERT INTO pledges (user_id,project_id,amount) VALUES (1,5,500);
INSERT INTO pledges (user_id,project_id,amount) VALUES (2,7,1000);
INSERT INTO pledges (user_id,project_id,amount) VALUES (3,4,450);
INSERT INTO pledges (user_id,project_id,amount) VALUES (4,2,700);
INSERT INTO pledges (user_id,project_id,amount) VALUES (5,1,100);
INSERT INTO pledges (user_id,project_id,amount) VALUES (6,10,250);
INSERT INTO pledges (user_id,project_id,amount) VALUES (7,9,5000);
INSERT INTO pledges (user_id,project_id,amount) VALUES (8,8,50);
INSERT INTO pledges (user_id,project_id,amount) VALUES (9,6,99);
INSERT INTO pledges (user_id,project_id,amount) VALUES (10,3,150);
INSERT INTO pledges (user_id,project_id,amount) VALUES (11,1,810);
INSERT INTO pledges (user_id,project_id,amount) VALUES (12,4,1500);
INSERT INTO pledges (user_id,project_id,amount) VALUES (13,2,600);
INSERT INTO pledges (user_id,project_id,amount) VALUES (14,3,550);
INSERT INTO pledges (user_id,project_id,amount) VALUES (15,6,40);
INSERT INTO pledges (user_id,project_id,amount) VALUES (16,10,350);
INSERT INTO pledges (user_id,project_id,amount) VALUES (17,9,200);
INSERT INTO pledges (user_id,project_id,amount) VALUES (18,6,500);
INSERT INTO pledges (user_id,project_id,amount) VALUES (19,5,80);
INSERT INTO pledges (user_id,project_id,amount) VALUES (20,4,120);
INSERT INTO pledges (user_id,project_id,amount) VALUES (4,7,1000);
INSERT INTO pledges (user_id,project_id,amount) VALUES (7,4,350);
INSERT INTO pledges (user_id,project_id,amount) VALUES (16,5,1200);
INSERT INTO pledges (user_id,project_id,amount) VALUES (19,10,400);
INSERT INTO pledges (user_id,project_id,amount) VALUES (6,2,10);
INSERT INTO pledges (user_id,project_id,amount) VALUES (3,9,500);
INSERT INTO pledges (user_id,project_id,amount) VALUES (7,8,650);
INSERT INTO pledges (user_id,project_id,amount) VALUES (12,1,1000);
INSERT INTO pledges (user_id,project_id,amount) VALUES (15,2,800);
INSERT INTO pledges (user_id,project_id,amount) VALUES (20,4,125);
