INSERT INTO users (name, age) VALUES ("Joshua", 22);
INSERT INTO users (name, age) VALUES ("Kenny", 21);
INSERT INTO users (name, age) VALUES ("Jonathan", 28);
INSERT INTO users (name, age) VALUES ("Tara", 23);
INSERT INTO users (name, age) VALUES ("Rosanna", 32);
INSERT INTO users (name, age) VALUES ("Wil", 28);
INSERT INTO users (name, age) VALUES ("Mena", 22);
INSERT INTO users (name, age) VALUES ("Kay", 21);
INSERT INTO users (name, age) VALUES ("Miles", 24);
INSERT INTO users (name, age) VALUES ("Rafael", 26);
INSERT INTO users (name, age) VALUES ("Jeff", 40);
INSERT INTO users (name, age) VALUES ("Ben", 33);
INSERT INTO users (name, age) VALUES ("Karl", 26);
INSERT INTO users (name, age) VALUES ("Buzz", 22);
INSERT INTO users (name, age) VALUES ("Rune", 26);
INSERT INTO users (name, age) VALUES ("Simon", 24);
INSERT INTO users (name, age) VALUES ("Michelle", 27);
INSERT INTO users (name, age) VALUES ("Matt", 33);
INSERT INTO users (name, age) VALUES ("Kevin", 31);
INSERT INTO users (name, age) VALUES ("Jane", 29);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The World", "book", 5000, "Mar 9", "Mar 8");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Pokemon Orange", "game", 12000, "Apr 8", "Dec 5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("JoJo Encyclopedia", "book", 31000, "Aug 23", "Feb 3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Life of Life", "book", 800, "Aug 23", "Jan 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Refactoring Ruby Again", "book", 1200, "Aug 2", "Oct 12");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Metaprogramming Made Easy", "book", 1000, "Oct 30", "Jan 3");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Debugging The Legend of Zelda", "book", 120000, "Dec 12", "Mar 19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Deadly Platypi", "game", 300000, "Mar 1", "May 5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("When JS Married Ruby", "book", 12300, "Sept 6", "Mar 2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES  ("Karma Collector", "game", 50, "Nov 11", "Dec 12");

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 20, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 5, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6000, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50400, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 1);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 20, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 5, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6000, 16, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50400, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 4);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6000, 16, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50400, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 5);
